var Fonts = [
"Abadi MT Condensed Extra Bold",
//"Abadi MT Condensed Light",
"Al Bayan",
"American Typewriter",
"Andale Mono",
"Apple Braille",
"Apple Chancery",
"Apple LiGothic",
"Apple LiSung",
"Apple Symbols",
"AppleGothic",
"AppleMyungjo",
"Arial",
"Arial Black",
"Arial Hebrew",
"Arial Narrow",
"Arial Rounded MT Bold",
"Arial Unicode MS",
"Ayuthaya",
"Baghdad",
"Baskerville",
"Baskerville Old Face",
"Batang",
"Bauhaus 93",
"Bell MT",
"Bernard MT Condensed",
"BiauKai",
"Big Caslon",
"BlairMdITC TT",
"Book Antiqua",
"Bookman Old Style",
"Bookshelf Symbol 7",
"Bordeaux Roman Bold LET",
"Braggadocio",
"Britannic Bold",
"Brush Script MT",
"Calibri",
"Calisto MT",
"Cambria",
"Candara",
"Casual",
"Century",
"Century Gothic",
"Century Schoolbook",
"Chalkboard",
"Chalkduster",
"Charcoal CY",
"Cochin",
"Colonna MT",
"Comic Sans MS",
"Consolas",
"Constantia",
"Cooper Black",
"Copperplate",
"Copperplate Gothic Bold",
"Copperplate Gothic Light",
"Corbel",
"Corsiva Hebrew",
"Courier",
"Courier New",
"Cracked",
"Curlz MT",
"DecoType Naskh",
"Desdemona",
"Devanagari MT",
"Didot",
"Edwardian Script ITC",
"Engravers MT",
"Euphemia UCAS",
"Eurostile",
"Footlight MT Light",
"Franklin Gothic Book",
"Franklin Gothic Medium",
"Futura",
"GB18030 Bitmap",
"Garamond",
"Geeza Pro",
"Geneva",
"Geneva CY",
"Georgia",
"Gill Sans",
"Gill Sans MT",
"Gill Sans Ultra Bold",
"Gloucester MT Extra Condensed",
"Goudy Old Style",
"Gujarati MT",
"Gulim",
"GungSeo",
"Gurmukhi MT",
"Haettenschweiler",
"Handwriting - Dakota",
"Harrington",
"HeadLineA",
"Hei",
"Heiti SC",
"Heiti TC",
"Helvetica",
"Helvetica CY",
"Helvetica Neue",
"Herculanum",
"Hiragino Kaku Gothic Pro",
"Hiragino Kaku Gothic ProN",
"Hiragino Kaku Gothic Std",
"Hiragino Kaku Gothic StdN",
"Hiragino Maru Gothic Pro",
"Hiragino Maru Gothic ProN",
"Hiragino Mincho Pro",
"Hiragino Mincho ProN",
"Hiragino Sans GB",
"Hoefler Text",
"Impact",
"Imprint MT Shadow",
"InaiMathi",
"Kai",
"Kailasa",
"Kino MT",
"Kokonor",
"Krungthep",
"KufiStandardGK",
"LiHei Pro",
"LiSong Pro",
"Lucida Blackletter",
"Lucida Bright",
"Lucida Calligraphy",
"Lucida Console",
"Lucida Fax",
"Lucida Grande",
"Lucida Handwriting",
"Lucida Sans",
"Lucida Sans Typewriter",
"Lucida Sans Unicode",
"MS Gothic",
"MS Mincho",
"MS PGothic",
"MS PMincho",
"MS Reference Sans Serif",
"MS Reference Specialty",
"MT Extra",
"Marker Felt",
"Marlett",
"Matura MT Script Capitals",
"Meiryo",
"Menlo",
"Microsoft Sans Serif",
"Mistral",
"Modern No. 20",
"Monaco",
"Monotype Corsiva",
"Monotype Sorts",
"Mshtakan",
"Nadeem",
"New Peninim MT",
"News Gothic MT",
"Onyx",
"Optima",
"Osaka",
"PCMyungjo",
"PMingLiU",
"Palatino",
"Papyrus",
"Perpetua",
"Perpetua Titling MT",
"PilGi",
"Plantagenet Cherokee",
"Playbill",
"PortagoITC TT",
"Raanana",
"Rockwell",
"Rockwell Extra Bold",
"STFangsong",
"STHeiti",
"STKaiti",
"STSong",
"Sathu",
"Silom",
"SimSun",
"Skia",
"Stencil",
"Symbol",
"Tahoma",
"Thonburi",
"Times",
"Times New Roman",
"Trebuchet MS",
"Tw Cen MT",
"Verdana",
"Webdings",
"Wide Latin",
"Wingdings",
"Wingdings 2",
"Wingdings 3",
"Zapf Dingbats",
  "Zapfino"];
